// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class ConteudoPedidosCliente
{
    public int? IdPedido { get; set; }

    public int? IdProduto { get; set; }

    public int? IdLote { get; set; }

    public int QtdProduto { get; set; }

    public virtual LotesProduto IdLoteNavigation { get; set; }

    public virtual TodosPedidosCliente IdPedidoNavigation { get; set; }

    public virtual Produto IdProdutoNavigation { get; set; }
}