// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class Entregadore
{
    public int IdEntregador { get; set; }

    public string NomeEntregador { get; set; }

    public int CpfEntregador { get; set; }

    public DateTime DataAdmissao { get; set; }

    public virtual ICollection<EntregaPedido> EntregaPedidos { get; set; } = new List<EntregaPedido>();
}