// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class EntregaPedido
{
    public int IdEntrega { get; set; }

    public int? IdEntregador { get; set; }

    public int? IdPedido { get; set; }

    public DateTime DataEntrega { get; set; }

    public string EnderecoEntrega { get; set; }

    public virtual Entregadore IdEntregadorNavigation { get; set; }

    public virtual TodosPedidosCliente IdPedidoNavigation { get; set; }

    public virtual ICollection<TodosPedidosCliente> TodosPedidosClientes { get; set; } = new List<TodosPedidosCliente>();
}