// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class Funcionario
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Cpf { get; set; }

    public string Telefone { get; set; }

    public string Endereço { get; set; }

    public string Email { get; set; }

    public string Senha { get; set; }
}