// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Telas_do_PIM.Models;

public partial class GenesisSolutionsContext : DbContext
{
    public GenesisSolutionsContext(DbContextOptions<GenesisSolutionsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Funcionario> Funcionarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Funcionario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Funciona__3214EC27F24928DA");

            entity.ToTable("Funcionario");

            entity.HasIndex(e => e.Email, "UQ__Funciona__161CF724A355946C").IsUnique();

            entity.HasIndex(e => e.Cpf, "UQ__Funciona__C1F89731EC1EBACC").IsUnique();

            entity.HasIndex(e => e.Telefone, "UQ__Funciona__D6F1694F5516FE8B").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Cpf)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("CPF");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.Endereço)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("ENDEREÇO");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Senha)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("SENHA");
            entity.Property(e => e.Telefone)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFONE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}