// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Telas_do_PIM.Models;

public partial class GenesisSolutionsContext : DbContext
{
    private readonly IConfiguration _configuration;
    public GenesisSolutionsContext()
        
    {
        _configuration = new ConfigurationBuilder()
           .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
           .Build();
    }

    public virtual DbSet<Funcionario> Funcionarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Funcionario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Funciona__3214EC27E9E855EF");

            entity.ToTable("Funcionario");

            entity.HasIndex(e => e.Email, "UQ__Funciona__161CF724A49F0C2A").IsUnique();

            entity.HasIndex(e => e.Cpf, "UQ__Funciona__C1F8973169FC9690").IsUnique();

            entity.HasIndex(e => e.Telefone, "UQ__Funciona__D6F1694F8BDAC63B").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Cpf)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("CPF");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.Endereço)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("ENDEREÇO");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Senha)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("SENHA");
            entity.Property(e => e.Telefone)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFONE");
        });

        OnModelCreatingPartial(modelBuilder);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(_configuration.GetSection("ConnectionStrings:AzureDB").Value);
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}