// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class Produto
{
    public int IdProduto { get; set; }

    public string NomeProduto { get; set; }

    public decimal ValorVenda { get; set; }

    public int QtdEmEstoque { get; set; }

    public byte[] ImagemProduto { get; set; }

    public virtual ICollection<LotesProduto> LotesProdutos { get; set; } = new List<LotesProduto>();

    public virtual ICollection<PedidosClienteDetalhe> PedidosClienteDetalhes { get; set; } = new List<PedidosClienteDetalhe>();
}