// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class Fornecedore
{
    public int IdFornecedor { get; set; }

    public string RazaoSocial { get; set; }

    public string Endereco { get; set; }

    public int? CnpjFornecedor { get; set; }

    public virtual ICollection<PedidosFornecedor> PedidosFornecedors { get; set; } = new List<PedidosFornecedor>();
}