// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class Insumo
{
    public int IdInsumo { get; set; }

    public string NomeInsumo { get; set; }

    public decimal? PrecoCusto { get; set; }
}