// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class LotesProduto
{
    public int IdLote { get; set; }

    public int? IdProduto { get; set; }

    public DateTime DataPlantio { get; set; }

    public DateTime DataColheita { get; set; }

    public int QtdProduzida { get; set; }

    public virtual Produto IdProdutoNavigation { get; set; }
}