// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class PedidosClienteDetalhe
{
    public int IdDetalhe { get; set; }

    public int? IdPedido { get; set; }

    public int Quantidade { get; set; }

    public decimal ValorUnitario { get; set; }

    public string Descricao { get; set; }

    public int? IdProduto { get; set; }

    public virtual PedidosCliente IdPedidoNavigation { get; set; }

    public virtual Produto IdProdutoNavigation { get; set; }
}