// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class PerfilTela
{
    public int Id { get; set; }

    public int? IdPerfil { get; set; }

    public int? IdTela { get; set; }

    public virtual Perfil IdPerfilNavigation { get; set; }

    public virtual Tela IdTelaNavigation { get; set; }
}