// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class Tela
{
    public int Id { get; set; }

    public string NomeTela { get; set; }

    public string IdentificacaoTela { get; set; }

    public virtual ICollection<PerfilTela> PerfilTelas { get; set; } = new List<PerfilTela>();
}