// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class TodosPedidosFornecedore
{
    public int IdPedido { get; set; }

    public decimal? ValorTotal { get; set; }

    public DateTime? DataAquisicao { get; set; }

    public string FormaPagto { get; set; }
}