// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Telas_do_PIM.Models;

public partial class TodosPedidosCliente
{
    public int IdPedido { get; set; }

    public int? IdEntrega { get; set; }

    public int ValorTotal { get; set; }

    public DateTime DataAquisicao { get; set; }

    public string FormaPagto { get; set; }

    public virtual ICollection<EntregaPedido> EntregaPedidos { get; set; } = new List<EntregaPedido>();

    public virtual EntregaPedido IdEntregaNavigation { get; set; }
}