//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pim_Frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Encomenda = new HashSet<Encomenda>();
        }
    
        public int Id { get; set; }
        public string CNPJ { get; set; }
        public string Senha { get; set; }
        public string Nome { get; set; }
        public string endereco_cliente { get; set; }
        public string Email { get; set; }
        public string CEP { get; set; }
        public string NUMERO { get; set; }
        public bool senha_criptografada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomenda { get; set; }
    }
}
