//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pim_Frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomenda
    {
        public int Id { get; set; }
        public int quantidade { get; set; }
        public string produto { get; set; }
        public Nullable<int> ClienteId { get; set; }
    
        public virtual Cliente Clientes { get; set; }
    }
}
